---
title: "Class Excercise 1"
author: "Miguel, Patrick Stöckli, Tobias Hoesli"
date: "`r Sys.Date()`"
output: pdf_document
urlcolor: 'blue'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

For this excersise we will be using the dataset **Quality of Governnment** Dataset. You can find the codebook [here](https://github.com/UniLuFS2020-ReplicationSeminar/Data_Mining_EX1/blob/f8314e3e5aef74dd7a3f3a26b7e0ffe7b2a4d3c3/data/codebook_bas_jan22.pdf).


### Regressionanalyisis




```{r Load TS Data and Regressions, warning=FALSE, message=FALSE}

source("../code/regression.R")

```

```{r Stargazer Regressionanalysis, results='asis'}
#Load package "labelled" to generate table
library(stargazer)

#Generate a well-formatted table
stargazer(regression_a, regression_b, regression_c, 
          title="Regression on the Share of Women in Parliament (Lower and Single Houses) ", 
          dep.var.caption="", 
          dep.var.labels.include=FALSE,
          covariate.labels=c("Islam","Level of Democracy", "Real GDP per Capita"), 
          digits=2,
          keep.stat=c("rsq", "adj.rsq", "n"), 
          notes=c("Notes: Standard errors in parentheses."), 
          notes.align = "c", 
          notes.label="",
          no.space=TRUE,
          type = 'latex')
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
